spring.application.name=obigo_ai_server

server.port=80
server.address=0.0.0.0

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# OpenAI Config
ai.openai.apiKeyEnv=OPENAI_API_KEY
ai.openai.baseUrl=https://api.openai.com/
ai.openai.defaultChatModel=gpt-4-turbo
ai.openai.defaultTemp=0.7

# Google Vision Config
ai.google.baseUrl=https://vision.googleapis.com/
ai.google.credentials.path=${GOOGLE_APPLICATION_CREDENTIALS:}
ai.google.credentials.json=
ai.google.scopes[0]=https://www.googleapis.com/auth/cloud-platform
ai.google.apiKeyEnv=GOOGLE_VISION_KEY

# log setting
logging.level.root=info
logging.level.com.obigo=debug
logging.level.com.obigo.tmobiportalboot.dao=debug
logging.level.jdbc=error
logging.level.jdbc.sqlonly=info
logging.level.log4jdbc.log4j2=error